sudo: required
services:
  - docker
before_install:
  - docker build -t jeremymiller/sudoku .
script:
  - docker run -it jeremymiller/sudoku swipl -s sudoku.pl -g "load_test_files(sudoku)." -g "run_tests." -t halt.
